### ISSUE TITLE
Inquery about how to test the guest

### ISSUE THREAD

**Issue by RuixiangJiang** [intel/tdx-guest#1]
Greetings! I'm excited about the new Rust guest implementation and eager to test it on my host VMM. I'm particularly interested in exploring the TDCALL and TDVMCALL implementations. I understand that I need to create a guest OS image based on a popular OS like Linux. Could you please provide guidance on constructing a guest image incorporating the Rust TDX? Thanks in advance!

**Comment by Hsy-Intel** [comment]
Thank you for your attention. This crate has been adopted in the [Asterinas](https://github.com/asterinas/asterinas) project, and TDX related documents are still being written. Please refer to the project if needed.

**Comment by RuixiangJiang** [comment]
Thanks for your answer! I looked into your folk of Asterinas, and I found in the branch 'os_tdx_env', there was a commit 'Add Intel TDX guide'. I have a TDX host, and I clone Asterinas into it, then run 'docker run -it --privileged --network=host --device=/dev/kvm -v asterinas:/root/asterinas asterinas/asterinas:0.4.2_tdx' to launch a Docker. However, it fails:
```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
? Please select an image: 
  ▸ registry.opensuse.org/asterinas/asterinas:0.4.2_tdx
    registry.suse.com/asterinas/asterinas:0.4.2_tdx
    docker.io/asterinas/asterinas:0.4.2_tdx
```
Here I choose all of them, as they are all failed. Take the third option as an example:
```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
✔ docker.io/asterinas/asterinas:0.4.2_tdx
Trying to pull docker.io/asterinas/asterinas:0.4.2_tdx...
Error: initializing source docker://asterinas/asterinas:0.4.2_tdx: reading manifest 0.4.2_tdx in docker.io/asterinas/asterinas: manifest unknown
```
And I reach to the docker hub page:
<img width="1297" alt="image" src="https://github.com/intel/tdx-guest/assets/30291784/83ad84a6-31d5-4c73-95b2-97c58845218c">
Could you provide further guidance? Thanks!

**Comment by RuixiangJiang** [comment]
I also wanna know what if I put the code in this repo to Asterinas and build the guest image on my own. Could I modify some codes in Asterinas to do that? Thanks!

**Comment by Hsy-Intel** [comment]
> Thanks for your answer! I looked into your folk of Asterinas, and I found in the branch 'os_tdx_env', there was a commit 'Add Intel TDX guide'. I have a TDX host, and I clone Asterinas into it, then run 'docker run -it --privileged --network=host --device=/dev/kvm -v asterinas:/root/asterinas asterinas/asterinas:0.4.2_tdx' to launch a Docker. However, it fails:
> 
> ```
> Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
> ? Please select an image: 
>   ▸ registry.opensuse.org/asterinas/asterinas:0.4.2_tdx
>     registry.suse.com/asterinas/asterinas:0.4.2_tdx
>     docker.io/asterinas/asterinas:0.4.2_tdx
> ```
> 
> Here I choose all of them, as they are all failed. Take the third option as an example:
> 
> ```
> Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
> ✔ docker.io/asterinas/asterinas:0.4.2_tdx
> Trying to pull docker.io/asterinas/asterinas:0.4.2_tdx...
> Error: initializing source docker://asterinas/asterinas:0.4.2_tdx: reading manifest 0.4.2_tdx in docker.io/asterinas/asterinas: manifest unknown
> ```
> 
> And I reach to the docker hub page: <img alt="image" width="1297" src="https://private-user-images.githubusercontent.com/30291784/331795466-83ad84a6-31d5-4c73-95b2-97c58845218c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTA0MDUsIm5iZiI6MTcxNjE5MDEwNSwicGF0aCI6Ii8zMDI5MTc4NC8zMzE3OTU0NjYtODNhZDg0YTYtMzFkNS00YzczLTk1YjItOTdjNTg4NDUyMThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA3MjgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjM2IxNWEyNDI0OTg0MmNkNTE0NDZhZDI2YzJlYWQ3NmZkM2M2ODU4MDcyNjE3YmIxZTlhNDI3MGZjZWUyMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mWNUyMs-Qd5lBiRiZvJgwx3Q5PGJT84aHtNYnzv6InQ"> Could you provide further guidance? Thanks!

This PR is still WIP, so you could not find the `asterinas/asterinas:0.4.2_tdx` Docker image. You can use the temporary Docker image `intelcczoo/asterinas:0.4.2_tdx`.

**Comment by Hsy-Intel** [comment]
> I also wanna know what if I put the code in this repo to Asterinas and build the guest image on my own. Could I modify some codes in Asterinas to do that? Thanks!

In fact, Asterinas is already using code from this repo. FYI: https://github.com/asterinas/asterinas/blob/main/framework/aster-frame/src/arch/x86/tdx_guest.rs

**Comment by RuixiangJiang** [comment]
Thanks! The `intelcczoo/asterinas:0.4.2_tdx` is available. Then I updated my local asterinas to the newest version and replaced the `tdx_guest.rs` using what you have provided (I used the commit [Refactor the definition of page properties and permissions](https://github.com/asterinas/asterinas/commit/989970429acc2b97137b8fc7a21be9f516b1aad5)). After that, I launched a QEMU using `make build BOOT_PROTOCOL=linux-efi-handover64 INTEL_TDX=1 SCHEME=tdx`. It raised some complied errors, and I fixed them.
Finally, it raised an error:
```
thread 'main' panicked at src/commands/build/mod.rs:178:13:
not yet implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [Makefile:129: build] Error 101
```
So I checked osdk/src/commands/build/mod.rs, and I found:
```
// line 177
BootMethod::GrubQcow2 => {
            todo!()
}
```
It seemed that the function was not completed yet, and the latest commit didn't indicate how to fill it. Could you give me some more instructions? Thanks for your patience!

**Comment by Hsy-Intel** [comment]
> Thanks! The `intelcczoo/asterinas:0.4.2_tdx` is available. Then I updated my local asterinas to the newest version and replaced the `tdx_guest.rs` using what you have provided (I used the commit [Refactor the definition of page properties and permissions](https://github.com/asterinas/asterinas/commit/989970429acc2b97137b8fc7a21be9f516b1aad5)). After that, I launched a QEMU using `make build BOOT_PROTOCOL=linux-efi-handover64 INTEL_TDX=1 SCHEME=tdx`. It raised some complied errors, and I fixed them. Finally, it raised an error:
> 
> ```
> thread 'main' panicked at src/commands/build/mod.rs:178:13:
> not yet implemented
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> make: *** [Makefile:129: build] Error 101
> ```
> 
> So I checked osdk/src/commands/build/mod.rs, and I found:
> 
> ```
> // line 177
> BootMethod::GrubQcow2 => {
>             todo!()
> }
> ```
> 
> It seemed that the function was not completed yet, and the latest commit didn't indicate how to fill it. Could you give me some more instructions? Thanks for your patience!

Yes, this work is in progress. you can choose a previous version (before using SCHEME=tdx) and you will get a .iso file. Then use 
`qemu-img convert -O qcow2 <iso file> <qcow2 file>` to convert it to qcow2 format. Finally you can use the `start-qemu.sh` in `tdx-tools` folder to load the kernel.

**Comment by RuixiangJiang** [comment]
Thanks for your patience! However, when I try to do this, I find my container failing to reach the Internet. Perhaps there is something wrong with the image `intelcczoo/asterinas:0.4.2_tdx` as everything went well two days ago. Are there some other images still available? Thanks in advance.

**Comment by Hsy-Intel** [comment]
> Thanks for your patience! However, when I try to do this, I find my container failing to reach the Internet. Perhaps there is something wrong with the image `intelcczoo/asterinas:0.4.2_tdx` as everything went well two days ago. Are there some other images still available? Thanks in advance.

Please try to unset the proxy: `unset http_proxy https_proxy`.

**Comment by RuixiangJiang** [comment]
I successfully get the qcow2 image, and I try to use this instruction to load the kernel:
```bash
#! /bin/bash
# author: pw0rld
# from https://github.com/SUSE/tdx-demo/tree/main
FILE=ast.qcow2

/usr/bin/qemu-system-x86_64 \
        -accel kvm \
        -object tdx-guest,sept-ve-disable=on,id=tdx0 \
        -object memory-backend-memfd-private,id=ram1,size=4G \
        -machine q35,kernel_irqchip=split,confidential-guest-support=tdx0,memory-backend=ram1 \
        -cpu host,pmu=off,-kvm-steal-time \
        -smp 1 \
        -drive file=${FILE},if=virtio \
        -netdev user,id=net0 \
        -device virtio-net,netdev=net0 \
        -vga none \
        --nographic \
        -bios /usr/share/qemu/tdvf-x86_64.bin\
        -virtfs local,path=/home/ruixiang_jiang/tdx-tools/attestation/pytdxmeasure,mount_tag=host0,security_model=passthrough


# in guest:
# sudo mount -t 9p -o trans-virtio,version=9p2000.L host0 .
```
And it fails:
<img width="1021" alt="image" src="https://github.com/intel/tdx-guest/assets/30291784/9f9dc2d5-6eeb-4a0a-be8e-0ab58568ee0a">
What does `ExitReason is 32` mean? I try to refer to the white papers but fail to find the error code. Could you give me some further instructions? Thanks!

**Comment by Hsy-Intel** [comment]
> I successfully get the qcow2 image, and I try to use this instruction to load the kernel:
> 
> ```shell
> #! /bin/bash
> # author: pw0rld
> # from https://github.com/SUSE/tdx-demo/tree/main
> FILE=ast.qcow2
> 
> /usr/bin/qemu-system-x86_64 \
>         -accel kvm \
>         -object tdx-guest,sept-ve-disable=on,id=tdx0 \
>         -object memory-backend-memfd-private,id=ram1,size=4G \
>         -machine q35,kernel_irqchip=split,confidential-guest-support=tdx0,memory-backend=ram1 \
>         -cpu host,pmu=off,-kvm-steal-time \
>         -smp 1 \
>         -drive file=${FILE},if=virtio \
>         -netdev user,id=net0 \
>         -device virtio-net,netdev=net0 \
>         -vga none \
>         --nographic \
>         -bios /usr/share/qemu/tdvf-x86_64.bin\
>         -virtfs local,path=/home/ruixiang_jiang/tdx-tools/attestation/pytdxmeasure,mount_tag=host0,security_model=passthrough
> 
> 
> # in guest:
> # sudo mount -t 9p -o trans-virtio,version=9p2000.L host0 .
> ```
> 
> And it fails: <img alt="image" width="1021" src="https://private-user-images.githubusercontent.com/30291784/332733626-9f9dc2d5-6eeb-4a0a-be8e-0ab58568ee0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NzUxMTEsIm5iZiI6MTcxNjc3NDgxMSwicGF0aCI6Ii8zMDI5MTc4NC8zMzI3MzM2MjYtOWY5ZGMyZDUtNmVlYi00YTBhLWJlOGUtMGFiNTg1NjhlZTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAxNTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YjQzMTBjNTQ2MThhZDM4NjNjMTA2ZjE1MjFiOTk3ZDRlYzM1ZTQ2NTdjYjYxZWYyNWY2ZTI3ZmRlZmE2MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sl6gJ70xTSq67RsZ0OXFjf7o785Wa-LOGuxV3FdS8hA"> What does `ExitReason is 32` mean? I try to refer to the white papers but fail to find the error code. Could you give me some further instructions? Thanks!

Please use the `stable` branch in my repo.
