### ISSUE TITLE
tdx-tools repo

### ISSUE THREAD

**Issue by wdsun1008** [intel/tdx-guest#2]
I have noticed that the tdx-tools repository is inaccessible. Is tdx now exclusively open to enterprise/cloud users only?

**Comment by Hsy-Intel** [comment]
No. The tdx-tools repo is deprecated. You can refer:
1. https://github.com/canonical/tdx
2. https://sigs.centos.org/virt/tdx/

**Comment by wdsun1008** [comment]
> No. The tdx-tools repo is deprecated. You can refer:
> 
> 1. https://github.com/canonical/tdx
> 2. https://sigs.centos.org/virt/tdx/

Thanks so much, I would recommend updating the Intel TDX documentation website and important partner documents (such as Nvidia H100 Confidential Mode with TDX).
